# <h1 style='color:#1B3A6B;'> PLAN DE ESTUDIO </h1>

----

# <span style='color:#2E86AB;'> Predicción de Cancelación de Clientes (Churn) para Interconnect </span>

---
# <span style='color:#1B3A6B;'> 1. ANÁLISIS EXPLORATORIO DE DATOS (EDA) </span>

In [1]:
# Importe de librerías
import pandas as pd
print('Librerías importadas exitosamente')

Librerías importadas exitosamente

In [4]:
# Carga de datasets

df_contract_orig = pd.read_csv('contract.csv')      # información del contrato
df_internet_orig = pd.read_csv('internet.csv')      # información sobre los servicios de Internet
df_personal_orig = pd.read_csv('personal.csv')      # datos personales del cliente
df_phone_orig    = pd.read_csv('phone.csv')         # información sobre los servicios telefónicos

# Generar copias
df_contract = df_contract_orig.copy()
df_internet = df_internet_orig.copy()
df_personal = df_personal_orig.copy()
df_phone    = df_phone_orig.copy()

# Generar diccionario
datasets = {'Contract' : df_contract,
            'Internet' : df_internet,
            'Personal' : df_personal,
            'Phone' : df_phone
           }

print("Datasets cargados correctamente")

Datasets cargados correctamente

In [5]:
# Exploración inicial de datos
for nombre, df in datasets.items():

    print(f'\n{"="*60}')
    print(f" {nombre.upper()} ")
    print(f'{"="*60}')

    print(f"\n📌 PRIMERAS 5 FILAS ")
    display(df.head())

    print(f"\n📌 INFORMACIÓN GENERAL")
    df.info()

    print(f"\n📌 ESTADÍSTICA DESCRIPTIVA ")
    display(df.describe(include='all').T)

    print(f"\n📌 DIMENCIONES DE DATOS")
    print(f"Número de filas       : {df.shape[0]}")
    print(f"Número de columnas    : {df.shape[1]}")
    print(f"Valores nulos totales : {df.isnull().sum().sum()}")
    print(f"Valores duplicados    : {df.duplicated().sum()}")
    

    print("--" * 40)

============================================================
 CONTRACT
============================================================

📌 PRIMERAS 5 FILAS

,customerID,BeginDate,EndDate,Type,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,7590-VHVEG,2020-01-01,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,5575-GNVDE,2017-04-01,No,One year,No,Mailed check,56.95,1889.5
2,3668-QPYBK,2019-10-01,2019-12-01 00:00:00,Month-to-month,Yes,Mailed check,53.85,108.15
3,7795-CFOCW,2016-05-01,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,9237-HQITU,2019-09-01,2019-11-01 00:00:00,Month-to-month,Yes,Electronic check,70.70,151.65

📌 INFORMACIÓN GENERAL
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   BeginDate         7043 non-null   object
 2   EndDate           7043 non-null   object
 3   Type              7043 non-null   object
 4   PaperlessBilling  7043 non-null   object
 5   PaymentMethod     7043 non-null   object
 6   MonthlyCharges    7043 non-null   float64
 7   TotalCharges      7043 non-null   object
dtypes: float64(1), object(7)
memory usage: 440.3+ KB

📌 ESTADÍSTICA DESCRIPTIVA

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customerID,7043,7043,9138-EFSMO,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BeginDate,7043,77,2014-02-01,366,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EndDate,7043,5,No,5174,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type,7043,3,Month-to-month,3875,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaperlessBilling,7043,2,Yes,4171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaymentMethod,7043,4,Electronic check,2365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MonthlyCharges,7043.0,NaN,NaN,NaN,64.761692,30.090047,18.25,35.5,70.35,89.85,118.75
TotalCharges,7043,6531,20.2,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN

📌 DIMENCIONES DE DATOS
Número de filas       : 7043
Número de columnas    : 8
Valores nulos totales : 0
Valores duplicados    : 0
--------------------------------------------------------------------------------

============================================================
 INTERNET
============================================================

📌 PRIMERAS 5 FILAS

,customerID,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Fiber optic,No,No,No,No,No,No

📌 INFORMACIÓN GENERAL
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5517 entries, 0 to 5516
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5517 non-null   object
 1   InternetService   5517 non-null   object
 2   OnlineSecurity    5517 non-null   object
 3   OnlineBackup      5517 non-null   object
 4   DeviceProtection  5517 non-null   object
 5   TechSupport       5517 non-null   object
 6   StreamingTV       5517 non-null   object
 7   StreamingMovies   5517 non-null   object
dtypes: object(8)
memory usage: 344.9+ KB

📌 ESTADÍSTICA DESCRIPTIVA

                 count unique          top  freq
customerID        5517   5517   9667-EQRXU     1
InternetService   5517      2  Fiber optic  3096
OnlineSecurity    5517      2           No  3498
OnlineBackup      5517      2           No  3088
DeviceProtection  5517      2           No  3095
TechSupport       5517      2           No  3473
StreamingTV       5517      2           No  2810
StreamingMovies   5517      2           No  2785

📌 DIMENCIONES DE DATOS
Número de filas       : 5517
Número de columnas    : 8
Valores nulos totales : 0
Valores duplicados    : 0
--------------------------------------------------------------------------------

============================================================
 PERSONAL
============================================================

📌 PRIMERAS 5 FILAS

   customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG  Female              0     Yes         No
1  5575-GNVDE    Male              0      No         No
2  3668-QPYBK    Male              0      No         No
3  7795-CFOCW    Male              0      No         No
4  9237-HQITU  Female              0      No         No

📌 INFORMACIÓN GENERAL
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   object
 1   gender         7043 non-null   object
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   object
 4   Dependents     7043 non-null   object
dtypes: int64(1), object(4)
memory usage: 275.2+ KB

📌 ESTADÍSTICA DESCRIPTIVA

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customerID,7043,7043,9138-EFSMO,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,7043,2,Male,3555,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SeniorCitizen,7043.0,NaN,NaN,NaN,0.162147,0.368612,0.0,0.0,0.0,0.0,1.0
Partner,7043,2,No,3641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dependents,7043,2,No,4933,NaN,NaN,NaN,NaN,NaN,NaN,NaN

📌 DIMENCIONES DE DATOS
Número de filas       : 7043
Número de columnas    : 5
Valores nulos totales : 0
Valores duplicados    : 0
--------------------------------------------------------------------------------

============================================================
 PHONE
============================================================

📌 PRIMERAS 5 FILAS

   customerID MultipleLines
0  5575-GNVDE            No
1  3668-QPYBK            No
2  9237-HQITU            No
3  9305-CDSKC           Yes
4  1452-KIOVK           Yes

📌 INFORMACIÓN GENERAL
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6361 entries, 0 to 6360
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     6361 non-null   object
 1   MultipleLines  6361 non-null   object
dtypes: object(2)
memory usage: 99.5+ KB

📌 ESTADÍSTICA DESCRIPTIVA

              count unique         top  freq
customerID     6361   6361  9138-EFSMO     1
MultipleLines  6361      2          No  3390

📌 DIMENCIONES DE DATOS
Número de filas       : 6361
Número de columnas    : 2
Valores nulos totales : 0
Valores duplicados    : 0
--------------------------------------------------------------------------------

In [5]:
# Resúmen de los 4 datasets
resumen = pd.DataFrame({
    nombre: {
        'Filas': df.shape[0],
        'Columnas': df.shape[1],
        'Nulos': df.isna().sum().sum(),
        'Duplicados': df.duplicated().sum()
    }
    for nombre, df in datasets.items()
}).T

display(resumen)

          Filas  Columnas  Nulos  Duplicados
Contract   7043         8      0           0
Internet   5517         8      0           0
Personal   7043         5      0           0
Phone      6361         2      0           0

---
# <span style='color: #1B3A6B;'> 2. LISTA DE PREGUNTAS ACLARATORIAS </span>
---

* ¿La fecha límite de los datos (1 feb 2020) implica que debo tratar clientes con EndDate posterior a esa fecha de forma distinta?

* Verifiqué que TotalCharges no corresponde exactamente a MonthlyCharges × antigüedad del cliente, hay diferencias de hasta varios cientos en algunos registros. ¿TotalCharges refleja cargos históricos con tarifas variables a lo largo del tiempo, o hay otro criterio de cálculo que deba considerar al usar esta variable como feature?


* ¿Debo evitar usar variables que dependan directamente de si el cliente canceló o no (como EndDate una vez que ya construí el target), o hay otras columnas derivadas que deba excluir explícitamente por posible fuga de información hacia el AUC-ROC?

* ¿El modelo final debe ser interpretable es decir, para que marketing entienda por qué o priorizamos desempeño puro?

---
# <span style='color:#1B3A6B;'> 3. PLAN APROXIMADO </span>
---

1. Preprocesamiento: unir las 4 tablas, construir el target de la columna EndDate (contract, target = 1 si EndDate ≠ 'No' [el cliente canceló], 0 si EndDate = 'No'), tratar nulos, codificar variables categóricas.


2. Análisis exploratorio y de correlaciones para identificar variables predictoras fuertes:

   * Revisar columnas nuevas derivadas a partir de EndDate y excluirlas, porque si no, el análisis de churn por categoría podría     calcularse sobre columnas contaminadas y dar conclusiones falsas. Luego analizar la distribución del target, y aplicar     boxplots para variables numéricas y tasa de churn por categoría con gráficos de barras para las categóricas.


3. Entrenar varios modelos base como (Logistic Regression, Random Forest, LightGBM/CatBoost) con validación cruzada y comparación de las métricas optenidos. 

4. Ajustar hiperparámetros y manejar el desbalance de clases (class_weight, upsampling, scale_pos_weight).

5. Evaluar en test con la métrica objetivo  y seleccionar el modelo final.